# Generated by Django 5.0.3 on 2024-06-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_alter_avaliacao_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
    ]
